import type { ConceptualMission } from "./types";

export const explorerPath = [
  { rank: "Rookie", body: "Foundation: fitness, navigation literacy, safety culture, and the discipline to not go." },
  { rank: "Novice Explorer", body: "Supervised field exposure. Equipment competence. Radio, weather and withdrawal drills." },
  { rank: "Field Explorer", body: "Reliable execution inside a known environment under a veteran lead." },
  { rank: "Specialist", body: "Domain depth: geology, biology, diving, alpine, cave, survey or recovery." },
  { rank: "Veteran", body: "Judgement under deteriorating conditions. Mentorship. Abort authority." },
  { rank: "Expedition Leader", body: "Mission design, permissions, team composition, and legal accountability." },
  { rank: "Frontier Specialist", body: "Rare combination of field mastery and research or engineering contribution." },
] as const;

export const explorationLoop = [
  "Train",
  "Certify",
  "Specialize",
  "Form team",
  "Accept mission",
  "Prepare",
  "Deploy",
  "Explore",
  "Collect",
  "Analyze",
  "Return",
  "Publish / commercialize",
  "Learn",
  "Upgrade capability",
] as const;

export const conceptualMissions: ConceptualMission[] = [
  {
    id: "CM-041",
    title: "High desert survey transect",
    type: "Geological survey",
    difficulty: "Demanding",
    expertise: ["Geology", "Survey", "Desert operations"],
    teamSize: "5 specialists",
    duration: "18 days",
    environment: "Arid plateau / high desert",
    scientificObjective: "Produce a high-resolution geological map and sample log along a defined transect.",
    equipment: ["GNSS survey kit", "Sample containers", "Shelter system", "Comms relay"],
    safety: "Heat protocol, water minimums, daily abort window",
    clientObjective: "University earth-science department requiring field data under chain-of-custody.",
    status: "Conceptual Mission",
  },
  {
    id: "CM-108",
    title: "Canopy and soil biodiversity grid",
    type: "Biological sampling",
    difficulty: "Severe",
    expertise: ["Field biology", "Jungle operations", "Data integrity"],
    teamSize: "6 specialists",
    duration: "24 days",
    environment: "Humid forest / river corridor",
    scientificObjective: "Establish a repeatable sampling grid for flora, soil and acoustic baseline.",
    equipment: ["Cold-chain cases", "Acoustic recorders", "Medical kit", "River craft"],
    safety: "Medical evacuation plan, waterborne disease controls, wildlife protocol",
    clientObjective: "Research institute preparing a longitudinal ecology program.",
    status: "Future Mission Framework",
  },
  {
    id: "CM-077",
    title: "Polar instrument endurance trial",
    type: "Equipment testing",
    difficulty: "Severe",
    expertise: ["Polar operations", "Electrical systems", "Risk assessment"],
    teamSize: "4 specialists",
    duration: "12 days",
    environment: "Coastal ice / katabatic wind field",
    scientificObjective: "Measure sensor drift, power loss and material failure under sustained cold.",
    equipment: ["Prototype sensor mast", "Power logger", "Cold-weather camp", "Beacon"],
    safety: "Cold injury limits, weather abort thresholds, redundant shelter",
    clientObjective: "Engineering group validating instruments before any later off-world analogue claim.",
    status: "Conceptual Mission",
  },
  {
    id: "CM-233",
    title: "Karst cave hydrological map",
    type: "Mapping",
    difficulty: "Extreme",
    expertise: ["Cave survey", "Hydrology", "Rescue-aware teaming"],
    teamSize: "5 specialists",
    duration: "9 days",
    environment: "Deep karst / restricted passages",
    scientificObjective: "Generate a legally shareable 3D cave map and water-flow notes.",
    equipment: ["LiDAR handheld", "Line and markers", "Gas monitors", "Haul system"],
    safety: "Gas limits, flood windows, surface watch, no unsupported penetration",
    clientObjective: "Environmental organization requiring a baseline before conservation planning.",
    status: "Future Mission Framework",
  },
];

export const missionClients = [
  "Universities",
  "Schools",
  "Research organizations",
  "Companies",
  "Scientific institutions",
  "Environmental organizations",
] as const;
