export const researchPrograms = [
  {
    slug: "workflow-intelligence",
    division: "primal" as const,
    horizon: "now" as const,
    title: "Workflow intelligence",
    body: "Methods for observing real operations, quantifying bottlenecks, and converting them into software that can be deployed and measured.",
  },
  {
    slug: "domain-ai-systems",
    division: "primal" as const,
    horizon: "now" as const,
    title: "Domain-specific AI systems",
    body: "Model, tool and interface patterns shaped by a particular industry’s language, risk and audit requirements.",
  },
  {
    slug: "extreme-robotics",
    division: "tech" as const,
    horizon: "building" as const,
    title: "Extreme-environment robotics",
    body: "A planned research direction in mobility, sensing and reliability where heat, cold, dust, pressure or isolation dominate.",
  },
  {
    slug: "spatial-interfaces",
    division: "tech" as const,
    horizon: "building" as const,
    title: "Spatial and teleoperation interfaces",
    body: "Human authority over distant machines through spatial interfaces — a prerequisite for later space telepresence.",
  },
  {
    slug: "computational-biology",
    division: "sciences" as const,
    horizon: "building" as const,
    title: "Computational biology",
    body: "Using models to compress experimental search space. A direction, not a catalogue of discoveries.",
  },
  {
    slug: "biological-information",
    division: "sciences" as const,
    horizon: "building" as const,
    title: "Biological information processing",
    body: "Long-horizon interest in neuroscience, neuromorphic and biohybrid computation.",
  },
  {
    slug: "allocation-systems",
    division: "capital" as const,
    horizon: "building" as const,
    title: "Capital allocation systems",
    body: "Institutional design for funding the next scientifically justified capability without theatrical return claims.",
  },
  {
    slug: "field-protocol",
    division: "exploration" as const,
    horizon: "frontier" as const,
    title: "Field protocol and expedition design",
    body: "Training, safety, permissions and scientific chain-of-custody as first-class engineering problems.",
  },
  {
    slug: "planetary-robotics",
    division: "space" as const,
    horizon: "future" as const,
    title: "Planetary robotics architecture",
    body: "Survey, manipulation, energy, communications and return as a single system. Objectives, not operations.",
  },
];
