import type { Scene } from "./types";

export const scenes: Scene[] = [
  {
    id: "signal",
    index: 0,
    start: 0,
    end: 0.08,
    chapter: "01 / SIGNAL",
    kicker: "WARAN INDUSTRIES",
    title: "The digital headquarters of a long-horizon industrial organization.",
    lines: ["INNOVATION", "EXPLORATION", "A BETTER TOMORROW"],
    body: "Beginning today. Architected for decades.",
    camera: { position: [0, 1.2, 8.5], target: [0, 0.4, 0], fov: 38 },
  },
  {
    id: "question",
    index: 1,
    start: 0.08,
    end: 0.16,
    chapter: "02 / QUESTION",
    kicker: "The unfinished map",
    title: "Humanity has built extraordinary systems.",
    lines: ["But entire frontiers remain difficult to understand,", "engineer and explore."],
    body: "WARAN exists to expand capability across technology, science, capital and exploration — honestly, in sequence.",
    camera: { position: [2.4, 1.6, 7.2], target: [0, 0.2, -1], fov: 40 },
  },
  {
    id: "primal",
    index: 2,
    start: 0.16,
    end: 0.28,
    chapter: "03 / FIRST FRONTIER",
    kicker: "Now · WARAN PRIMAL",
    title: "AI that transforms work.",
    lines: ["Observe.", "Understand.", "Build.", "Scale."],
    body: "The only current operating division. AI-native software that turns operational bottlenecks into scalable systems. Everything begins here.",
    status: "now",
    href: "/divisions/primal",
    camera: { position: [-0.4, 1.1, 6.2], target: [0, 0.3, -2.2], fov: 36 },
  },
  {
    id: "tech",
    index: 3,
    start: 0.28,
    end: 0.38,
    chapter: "04 / ENGINE",
    kicker: "Building · WARAN TECH",
    title: "Machines extend human reach.",
    lines: ["Robotics.", "Autonomy.", "Extreme environments."],
    body: "A planned advanced technology division. Not consumer gadgets. Engineered systems for the physical world software cannot enter.",
    status: "building",
    href: "/divisions/tech",
    camera: { position: [3.2, 1.4, 5.4], target: [1.2, 0.4, -3.4], fov: 34 },
  },
  {
    id: "sciences",
    index: 4,
    start: 0.38,
    end: 0.48,
    chapter: "05 / BIOLOGICAL FRONTIER",
    kicker: "Building · WARAN SCIENCES",
    title: "Computation meets biology.",
    lines: ["Models.", "Molecules.", "Method."],
    body: "A research direction in computational biology, protein engineering and biological information processing. No results are claimed.",
    status: "building",
    href: "/divisions/sciences",
    camera: { position: [-3.4, 1.8, 5.8], target: [-1.4, 0.5, -3.8], fov: 34 },
  },
  {
    id: "capital",
    index: 5,
    start: 0.48,
    end: 0.57,
    chapter: "06 / CAPITAL ENGINE",
    kicker: "Building · WARAN CAPITAL",
    title: "Capital becomes an instrument of progress.",
    lines: ["Allocate.", "Underwrite.", "Endure."],
    body: "Institutional capital intelligence designed to fund the next necessary capability. No returns, funds or performance are shown.",
    status: "building",
    href: "/divisions/capital",
    camera: { position: [0.2, 2.4, 7.4], target: [0, 0.2, -4.2], fov: 32 },
  },
  {
    id: "exploration",
    index: 6,
    start: 0.57,
    end: 0.67,
    chapter: "07 / EARTHLY FRONTIER",
    kicker: "Frontier · WARAN EXPLORATION",
    title: "Train. Prepare. Explore. Discover.",
    lines: ["Protocol before terrain.", "Teams, not tourists."],
    body: "A planned professional expedition architecture. Conceptual missions only. Safety, permissions and scientific method are the point.",
    status: "frontier",
    href: "/divisions/exploration",
    camera: { position: [4.2, 2.8, 8.6], target: [0.6, 0.1, -5.2], fov: 38 },
  },
  {
    id: "machine",
    index: 7,
    start: 0.67,
    end: 0.75,
    chapter: "08 / FURTHER",
    kicker: "The machine goes further",
    title: "Robotics for environments humans should not have to enter first.",
    lines: ["Autonomy.", "Teleoperation.", "Field proof."],
    body: "Before space, the same logic must work on Earth: machines in heat, ice, dark, pressure and distance.",
    status: "frontier",
    camera: { position: [1.4, 1.6, 5.2], target: [0.2, 0.0, -6.4], fov: 30 },
  },
  {
    id: "space",
    index: 8,
    start: 0.75,
    end: 0.86,
    chapter: "09 / BEYOND EARTH",
    kicker: "Future · WARAN SPACE",
    title: "Beyond Earth. For a greater future.",
    lines: ["Moon.", "Mars.", "Asteroids.", "Beyond."],
    body: "A long-range robotics-first objective. Not an operating space program. Humans keep authority. Machines take the early risk.",
    status: "future",
    href: "/divisions/space",
    camera: { position: [0, 3.6, 14], target: [0, 0.2, -10], fov: 42 },
  },
  {
    id: "system",
    index: 9,
    start: 0.86,
    end: 0.93,
    chapter: "10 / SYSTEM",
    kicker: "The flywheel",
    title: "The divisions are one industrial organism.",
    lines: ["Software funds capability.", "Capability returns discovery.", "Discovery becomes the next system."],
    body: "Interact with any node and the related divisions illuminate. WARAN is coherent because the loops are designed, not because every loop is already running.",
    href: "/#system",
    camera: { position: [0, 4.8, 11], target: [0, 0.4, -2], fov: 36 },
  },
  {
    id: "future",
    index: 10,
    start: 0.93,
    end: 0.975,
    chapter: "11 / FUTURE",
    kicker: "Capability, not a product line",
    title: "WARAN is not building one product.",
    lines: ["It is building the capacity to keep going."],
    body: "A company that can add divisions, missions and research programs without rewriting its reason to exist.",
    camera: { position: [0, 2.2, 9.5], target: [0, 0.6, 0], fov: 34 },
  },
  {
    id: "cta",
    index: 11,
    start: 0.975,
    end: 1,
    chapter: "12 / ENTER",
    kicker: "Build with WARAN",
    title: "The organization is real enough to begin.",
    lines: ["Build.", "Research.", "Explore.", "Partner."],
    body: "Start at PRIMAL. The rest is architecture — visible, sequential, and not pretended into existence.",
    href: "/contact",
    camera: { position: [0, 1.1, 7.2], target: [0, 0.35, 0], fov: 36 },
  },
];

export function sceneAt(progress: number) {
  const p = Math.min(1, Math.max(0, progress));
  return scenes.find((scene) => p >= scene.start && p < scene.end) ?? scenes[scenes.length - 1];
}

export function sceneLocalProgress(progress: number, scene = sceneAt(progress)) {
  const span = Math.max(0.0001, scene.end - scene.start);
  return Math.min(1, Math.max(0, (progress - scene.start) / span));
}
